[package]
name = "distrust"
version = "0.1.0"
authors = ["Thejesvini Rachapudi <thejesvini@joinroot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
rayon = "1.5.0"